---
author: "William Stockhausen"
date: '`r format(Sys.Date(),"%d %B, %Y")`'
params: 
    Models: none
    title: "Comparisons of Input Data to the Tanner Crab Model" 
    doc_type: "pdf"
    InputData:
      !r list(includeSurveyData=TRUE,
              surveys=list(plotAbundance=TRUE,
                           plotBiomass=TRUE,
                           plotZCs=TRUE,
                           plot1stObs=FALSE,
                           fleets="all",
                           ci=0.80,
                           numRecent=30),
              includeFisheryData=TRUE,
              fisheries=list(fleets="all",
                             retained=list(plotAbundance=TRUE,
                                           plotBiomass=TRUE,
                                           plotZCs=TRUE,
                                           plot1stObs=FALSE,
                                           ci=0.80,
                                           numRecent=30),
                             total=list(plotAbundance=TRUE,
                                           plotBiomass=TRUE,
                                           plotZCs=TRUE,
                                           plot1stObs=FALSE,
                                           ci=0.80,
                                           numRecent=30),
                             effort=list(plot=TRUE,
                                         plot1stObs=FALSE,
                                         numRecent=30)),
              includeGrowthData=TRUE,
              includeMaturityOgiveData=TRUE,                           
              verbose=FALSE)
output: 
    word_document: 
        reference_docx: '`r system.file("rmd/StylesforRmdDocs.docx",package="wtsUtilities")`'
    pdf_document: 
        toc: TRUE
        fig_width: 6.5
        fig_height: 4.0
        fig_crop: FALSE
        fig_caption: TRUE
        includes:
          in_header: '`r system.file("rmd/StylesforRmdPDFs.sty",package="wtsUtilities")`'
fontsize: 11pt
title: '`r params$title`'
---

```{r setupInputData_Surveys, include=FALSE}
    ##input model list
    Models<-params$Models;
    doc_type<-params$doc_type;
    verbose = params$InputSurveyData$verbose;
    
    ##set appendix letter
    app="A";
    ##set knitr options for subsequent chunks
    knitr::opts_chunk$set(echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, concordance=TRUE, fig.width=6.5, fig.height=7.0, dpi=300)
    
    ##set caption numbering
    if (!exists("fig")){
      fig<-1;#figures
      tbl<-0;#tables
    }
    
    cases<-names(Models);
    nCases<-length(cases);
```

# Input data

```{r plotData.SurveysDataSection,results='asis'}
  if (params$InputData$includeSurveyData){
    cat("\n\#\# Survey data\n\n")
  }
```

### Survey biomass

```{r plotData.SurveyBiomass,results='asis',fig.height=8.0,fig.width=6.5,out.width="6.5in",fig.cap=captions,eval.after="fig.cap",fig.pos="H"}
  if (params$InputData$plotBiomass){
    message("starting plotData.SurveyBiomass")
    plts<-rCompTCMs::compareData.FleetTimeSeriesABsa(Models,fleet.type='survey',catch.type='index',data.type="biomass",
                                                     fleets=params$InputData$surveys$fleets,
                                                     ci=params$InputData$surveys$ci,
                                                     plot1stObs=params$InputData$surveys$plot1stObs,
                                                     numRecent=params$InputData$surveys$numRecent,
                                                     verbose=verbose);
    if (!is.null(plts)){
      captions<-wtsUtilities::getCaptionsFromGGPlotList(plts);
      for (plt in plts) {print(plt); cat("\n\n"); fig<-fig+1;}
      rm(plt,plts);
    } else {
        cat("\nNo survey biomass data.\n\n")
    }
  } else {
    cat("\nPlots of survey biomass data not included.\n\n")
  }
```

\FloatBarrier

\clearpage

## Survey abundance

```{r plotFits.SurveyAbundance,results='asis',fig.height=8.0,fig.width=6.5,out.width="6.5in",fig.cap=captions,eval.after="fig.cap",fig.pos="H"}
  message("starting plotFits.ZScores.SurveyBiomass")
  plts<-rCompTCMs::compareFits.AbundanceData(Models,fleet.type='survey',catch.type='index',plot1stObs=plot1stObs,verbose=FALSE,numRecent=numRecent);
  if (!is.null(plts)){
      captions<-wtsUtilities::getCaptionsFromGGPlotList(plts);
      for (plt in plts) {print(plt); cat("\n\n"); fig<-fig+1;}
      rm(plt,plts);
  } else {
        cat("\nNo fits to survey abundance data.\n\n")
    }
```

```{r plotFits.ZScores.SurveyAbundance,results='asis',fig.height=7.0,fig.width=6.5,out.width="6.5in",fig.cap=captions,eval.after="fig.cap",fig.pos="H"}
  message("starting plotFits.ZScores.SurveyBiomass")
    plts<-rCompTCMs::compareFits.ZScores.Abundance(Models,fleet.type='survey',catch.type='index',verbose=FALSE);
    if (!is.null(plts)){
        captions<-wtsUtilities::getCaptionsFromGGPlotList(plts);
        for (plt in plts) {print(plt); cat("\n\n"); fig<-fig+1;}
        rm(plt,plts);
    } else {
        cat("\nNo z-scores for fits to survey biomass data.\n\n")
    }
```

\FloatBarrier

\clearpage

## Fishery retained catch biomass

```{r plotFits.FisheryRetainedCatchBiomass,results='asis',fig.height=8.0,fig.width=6.5,out.width="6.5in",fig.cap=captions,eval.after="fig.cap",fig.pos="H"}
  message("starting plotFits.ZScores.SurveyBiomass")
    plts<-rCompTCMs::compareFits.BiomassData(Models,fleet.type='fishery',catch.type='retained',plot1stObs=plot1stObs,verbose=FALSE,numRecent=numRecent);
    if (!is.null(plts)){
        captions<-wtsUtilities::getCaptionsFromGGPlotList(plts);
        for (plt in plts) {print(plt); cat("\n\n"); fig<-fig+1;}
        rm(plt,plts);
    } else {
        cat("\nNo fits to fishery retained catch biomass data.\n\n")
    }
```

```{r plotFits.ZScores.FisheryRetainedCatchBiomass,results='asis',fig.height=7.0,fig.width=6.5,out.width="6.5in",fig.cap=captions,eval.after="fig.cap",fig.pos="H"}
  message("starting plotFits.ZScores.SurveyBiomass")
    plts<-rCompTCMs::compareFits.ZScores.Biomass(Models,fleet.type='fishery',catch.type='retained',verbose=FALSE);
    if (!is.null(plts)){
        captions<-wtsUtilities::getCaptionsFromGGPlotList(plts);
        for (plt in plts) {print(plt); cat("\n\n"); fig<-fig+1;}
        rm(plt,plts);
    } else {
        cat("\nNo z-scores for fits to fishery retained catch biomass data.\n\n")
    }
```

\FloatBarrier

\clearpage

## Fishery retained catch abundance

```{r plotFits.FisheryRetainedCatchAbundance,results='asis',fig.height=8.0,fig.width=6.5,out.width="6.5in",fig.cap=captions,eval.after="fig.cap",fig.pos="H"}
  message("starting plotFits.ZScores.SurveyBiomass")
    plts<-rCompTCMs::compareFits.AbundanceData(Models,fleet.type='fishery',catch.type='retained',plot1stObs=plot1stObs,verbose=FALSE,numRecent=numRecent);
    if (!is.null(plts)){
        captions<-wtsUtilities::getCaptionsFromGGPlotList(plts);
        for (plt in plts) {print(plt); cat("\n\n"); fig<-fig+1;}
        rm(plt,plts);
    } else {
        cat("\nNo fits to fishery retained catch abundance data.\n\n")
    }
```

```{r plotFits.ZScores.FisheryRetainedCatchAbundances,results='asis',fig.height=7.0,fig.width=6.5,out.width="6.5in",fig.cap=captions,eval.after="fig.cap",fig.pos="H"}
  message("starting plotFits.ZScores.SurveyBiomass")
    plts<-rCompTCMs::compareFits.ZScores.Abundance(Models,fleet.type='fishery',catch.type='retained',verbose=FALSE);
    if (!is.null(plts)){
        captions<-wtsUtilities::getCaptionsFromGGPlotList(plts);
        for (plt in plts) {print(plt); cat("\n\n"); fig<-fig+1;}
        rm(plt,plts);
    } else {
        cat("\nNo z-scores for fits to fishery retained catch abundance data.\n\n")
    }
```

\FloatBarrier

\clearpage

## Fishery total catch biomass

```{r plotFits.FisheryTotalCatchBiomass,results='asis',fig.height=7.0,fig.width=6.5,out.width="6.5in",fig.cap=captions,eval.after="fig.cap",fig.pos="H"}
  message("starting plotFits.ZScores.SurveyBiomass")
    plts<-rCompTCMs::compareFits.BiomassData(Models,fleet.type='fishery',catch.type='total',plot1stObs=plot1stObs,verbose=FALSE,numRecent=numRecent);
    if (!is.null(plts)){
        captions<-wtsUtilities::getCaptionsFromGGPlotList(plts);
        for (plt in plts) {print(plt); cat("\n\n"); fig<-fig+1;}
        rm(plt,plts);
    } else {
        cat("\nNo fits to fishery total catch biomass data.\n\n")
    }
```

```{r plotFits.ZScores.FisheryTotalCatchBiomass,results='asis',fig.height=8.0,fig.width=6.5,out.width="6.5in",fig.cap=captions,eval.after="fig.cap",fig.pos="H"}
  message("starting plotFits.ZScores.SurveyBiomass")
    plts<-rCompTCMs::compareFits.ZScores.Biomass(Models,fleet.type='fishery',catch.type='total',verbose=FALSE);
    if (!is.null(plts)){
        captions<-wtsUtilities::getCaptionsFromGGPlotList(plts);
        for (plt in plts) {print(plt); cat("\n\n"); fig<-fig+1;}
        rm(plt,plts);
    } else {
        cat("\nNo z-scores for fits to fishery total catch biomass data.\n\n")
    }
```

\FloatBarrier

\clearpage

## Fishery total catch abundance

```{r plotFits.FisheryTotalCatchAbundance,results='asis',fig.height=8.0,fig.width=6.5,out.width="6.5in",fig.cap=captions,eval.after="fig.cap",fig.pos="H"}
  message("starting plotFits.ZScores.SurveyBiomass")
    plts<-rCompTCMs::compareFits.AbundanceData(Models,fleet.type='fishery',catch.type='total',plot1stObs=plot1stObs,verbose=FALSE,numRecent=numRecent);
    if (!is.null(plts)){
        captions<-wtsUtilities::getCaptionsFromGGPlotList(plts);
        for (plt in plts) {print(plt); cat("\n\n"); fig<-fig+1;}
        rm(plt,plts);
    } else {
        cat("\nNo z-scores for fits to fishery total catch abundance data.\n\n")
    }
```

```{r plotFits.ZScores.FisheryTotalCatchAbundance,results='asis',fig.height=7.0,fig.width=6.5,out.width="6.5in",fig.cap=captions,eval.after="fig.cap",fig.pos="H"}
  message("starting plotFits.ZScores.SurveyBiomass")
    plts<-rCompTCMs::compareFits.ZScores.Abundance(Models,fleet.type='fishery',catch.type='total',verbose=FALSE);
    if (!is.null(plts)){
        captions<-wtsUtilities::getCaptionsFromGGPlotList(plts);
        for (plt in plts) {print(plt); cat("\n\n"); fig<-fig+1;}
        rm(plt,plts);
    } else {
        cat("\nNo z-scores for fits to fishery total catch abundance data.\n\n")
    }
```
