---
author: "William Stockhausen"
date: '`r format(Sys.Date(),"%d %B, %Y")`'
params: 
    Models: none
    title: "Tanner Crab Model Comparisons" 
    doc_type: "pdf"
    includeInputData: FALSE
    InputData:
      !r list(includeSurveyData=TRUE,
              surveys=list(plotAbundance=TRUE,
                           plotBiomass=TRUE,
                           plotZCs=TRUE,
                           plot1stObs=FALSE,
                           fleets="all",
                           ci=0.80,
                           numRecent=30),
              includeFisheryData=TRUE,
              fisheries=list(fleets="all",
                             retained=list(plotAbundance=TRUE,
                                           plotBiomass=TRUE,
                                           plotZCs=TRUE,
                                           plot1stObs=FALSE,
                                           ci=0.80,
                                           numRecent=30),
                             total=list(plotAbundance=TRUE,
                                           plotBiomass=TRUE,
                                           plotZCs=TRUE,
                                           plot1stObs=FALSE,
                                           ci=0.80,
                                           numRecent=30),
                             effort=list(plot=TRUE,
                                         plot1stObs=FALSE,
                                         numRecent=30)),
              includeGrowthData=TRUE,
              includeMaturityOgiveData=TRUE,                           
              verbose=FALSE)
    includePopProcesses: FALSE
    PopProcesses:
      !r list(verbose=FALSE)
    includePopQuantities: FALSE
    PopQuantities:
      !r list(verbose=FALSE)
    includeModelFitsToOtherData: FALSE
    ModelFitsToOtherData:
      !r list(plot1stObs=TRUE,
             minSizeForMaturityData=60,
             verbose=FALSE)
    includeModelFitsACD: FALSE
    ModelFitsACD:
      !r list(plot1stObs=TRUE,
             numRecent=30,
             verbose=FALSE)
    includeModelFitsZCs: FALSE
    ModelFitsZCs:
      !r list(plot1stObs=TRUE,
             fleets="all",
             verbose=FALSE)
    includeCharacteristicsSurveys: TRUE
    CharacteristicsSurveys:
      !r list(plot1stObs=TRUE,
             fleets="all",
             selyears="all",
             avlyears="all",
             capyears="all",
             mxy=5,
             verbose=FALSE)
    includeCharacteristicsFisheries: FALSE
    CharacteristicsFisheries:
      !r list(plot1stObs=TRUE,
             fleets="all",
             selyears="all",
             retyears="all",
             verbose=FALSE)
    includeParameterTables: FALSE
    ParameterTables:
      !r list(verbose=FALSE)
output: 
    word_document: 
        reference_docx: '`r system.file("rmd/StylesforRmdDocs.docx",package="wtsUtilities")`'
    pdf_document: 
        toc: TRUE
        fig_width: 6.5
        fig_height: 4.0
        fig_crop: FALSE
        fig_caption: TRUE
        keep_tex: FALSE
        includes:
          in_header: '`r system.file("rmd/StylesforRmdPDFs.sty",package="wtsUtilities")`'
fontsize: 11pt
title: '`r params$title`'
---

```{r setup,echo=FALSE,results='hide'}
  ##input model list
  Models<-params$Models;
  doc_type<-params$doc_type;
  
  ##set appendix letter
  app="A";
  ##set knitr options for subsequent chunks
  knitr::opts_chunk$set(echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, concordance=TRUE, fig.width=6.5, fig.height=3.5, dpi=300)
  
  ##set caption numbering
  fig<-1;#figures
  tbl<-0;#tables

  cases<-names(Models);
  nCases<-length(cases);
```

\setcounter{tocdepth}{3}

\addcontentsline{toc}{section}{List of Tables in Model Comparisons}
\listoftables

\addcontentsline{toc}{section}{List of Figures in Model Comparisons}
\listoffigures

\newpage

```{r modelComparisons_InputData,results='asis',echo=FALSE}
  if (params$includeInputData){
    cat("\n\\newpage\n")
    path = system.file("rmd/modelComparisons.InputData.Rmd",package="rCompTCMs");
    fn   = basename(path);
    message("child rmd file:",fn)
    cat(
      knitr::knit_child(fn,envir=environment(),quiet=TRUE)
    )
  } else {
    message("Skipping modelComparisons_InputData")
  }
```

```{r modelComparisons_PopProcesses,results="asis",echo=FALSE}
  if (params$includePopProcesses){
    cat("\n\\newpage\n")
    path = system.file("rmd/modelComparisons.PopProcesses.Rmd",package="rCompTCMs");
    fn   = basename(path);
    message("child rmd file:",fn)
    cat(
      knitr::knit_child(fn,envir=environment(),quiet=TRUE)
    )
  } else {
    message("Skipping modelComparisons_PopProcesses")
  }
```

```{r modelComparisons_PopQuantities,results="asis",echo=FALSE}
  if (params$includePopQuantities){
    cat("\n\\newpage\n")
    path = system.file("rmd/modelComparisons.PopQuantities.Rmd",package="rCompTCMs");
    fn   = basename(path);
    message("child rmd file:",fn)
    cat(
      knitr::knit_child(fn,envir=environment(),quiet=TRUE)
    )
  } else {
    message("Skipping modelComparisons_PopQuantities")
  }
```

```{r modelComparisons_ModelFitsACD,results='asis',echo=FALSE}
  if (params$includeModelFitsACD){
    cat("\n\\newpage\n")
    path = system.file("rmd/modelComparisons.ModelFits.ACD.Rmd",package="rCompTCMs");
    fn   = basename(path);
    message("child rmd file:",fn)
    cat(
      knitr::knit_child(fn,envir=environment(),quiet=TRUE)
    )
  } else {
    message("Skipping modelComparisons_ModelFitsACD")
  }
```

```{r modelComparisons_ModelFitsZCs,results='asis',echo=FALSE}
  if (params$includeModelFitsZCs){
    cat("\n\\newpage\n")
    path = system.file("rmd/modelComparisons.ModelFits.ZCs.All.Rmd",package="rCompTCMs");
    fn   = basename(path);
    message("child rmd file:",fn)
    cat(
      knitr::knit_child(fn,envir=environment(),quiet=TRUE)
    )
  } else {
    message("Skipping modelComparisons_ModelFitsZCs")
  }
```

```{r modelComparisons_ModelFitsToOtherData,results="asis",echo=FALSE}
  if (params$includeModelFitsToOtherData){
    cat("\n\\newpage\n")
    path = system.file("rmd/modelComparisons.ModelFits.OtherData.Rmd",package="rCompTCMs")
    fn   = basename(path);
    message("child rmd file:",fn)
    cat(
      knitr::knit_child(fn,envir=environment(),quiet=TRUE)
    )
  } else {
    message("Skipping modelComparisons_ModelFitsToOtherData")
  }
```

```{r modelComparisons_CharacteristicsSurveys,results='asis',echo=FALSE}
  if (params$includeCharacteristicsSurveys){
    cat("\n\\newpage\n")
    path = system.file("rmd/modelComparisons.EstimatedCharacteristics.Surveys.Rmd",package="rCompTCMs");
    fn   = basename(path);
    message("child rmd file:",fn)
    cat(
      knitr::knit_child(fn,envir=environment(),quiet=TRUE)
    )
  } else {
    message("Skipping modelComparisons_CharacteristicsSurveys")
  }
```

```{r modelComparisons.Characteristics.Fisheries,results='asis',echo=FALSE}
  if (params$includeCharacteristicsFisheries){
    cat("\n\\newpage\n")
    path = system.file("rmd/modelComparisons.EstimatedCharacteristics.Fisheries.Rmd",package="rCompTCMs");
    fn   = basename(path);
    message("child rmd file:",fn)
    cat(
      knitr::knit_child(fn,envir=environment(),quiet=TRUE)
    )
  } else {
    message("Skipping modelComparisons_CharacteristicsFisheries")
  }
```

```{r modelComparisons_ParameterTables,results='asis',echo=FALSE}
  if (params$includeParameterTables){
    cat("\n\\newpage\n")
    path = system.file("rmd/modelComparisons.ParameterTables.Rmd",package="rCompTCMs");
    fn   = basename(path);
    message("child rmd file:",fn)
    cat(
      knitr::knit_child(fn,envir=environment(),quiet=TRUE)
    )
  } else {
    message("Skipping modelComparisons_ParameterTables")
  }
```

