---
author: "William Stockhausen"
date: '`r format(Sys.Date(),"%d %B, %Y")`'
params: 
    Models: none
    title: "Tanner Crab Assessment Model: Estimated Fishery Characteristics" 
    plot1stObs: TRUE
    fleets: "all"
    selyears: "all"
    retyears: "all"
    doc_type: "pdf"
    verbose: FALSE
output: 
    word_document: 
        reference_docx: '`r system.file("rmd/StylesforRmdDocs.docx",package="wtsUtilities")`'
    pdf_document: 
        toc: TRUE
        fig_width: 6.5
        fig_height: 4.0
        fig_crop: FALSE
        fig_caption: TRUE
        includes:
          in_header: '`r system.file("rmd/StylesforRmdPDFs.sty",package="wtsUtilities")`'
fontsize: 11pt
title: '`r params$title`'
---

```{r setupFisheryCharacteristics, include=FALSE}
    ##input model list
    Models<-params$Models;
    doc_type<-params$doc_type;
    plot1stObs<-params$plot1stObs;
    verbose<-params$verbose;
    cat("verbose = ",verbose,"\n")
    
    ##set knitr options for subsequent chunks
    knitr::opts_chunk$set(echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, concordance=TRUE, fig.width=6.5, fig.height=7.0, dpi=300)
    
    ##set caption numbering
    if (!exists("fig")){
      fig<-1;#figures
      tbl<-0;#tables
    }
    
    cases<-names(Models);
    nCases<-length(cases);
```

# Introduction
Model-estimated fishery characteristics such as catchability and selectivity and retention functions are presented in this section.

\clearpage

# Fishery catchability

```{r EFCs01.Catchability,results='asis',fig.height=6.5,fig.width=6.5,out.width="6.5in",fig.cap=captions,eval.after="fig.cap",fig.pos="H"}
  plts<-rCompTCMs::compareResults.Fisheries.Catchability(Models,
                                                         fleets=params$fleets,
                                                         dodge=0,
                                                         showPlot=FALSE,
                                                         verbose=verbose)
  captions<-wtsUtilities::getCaptionsFromGGPlotList(plts);
  for (plt in plts) {print(plt); cat("\n\n"); fig<-fig+1;}
  rm(plt,plts);
```

\FloatBarrier

\clearpage 

# Total selectivity functions

```{r EFCs02.SelFcns,results='asis',fig.height=6.5,fig.width=6.5,out.width="6.5in",fig.cap=captions,eval.after="fig.cap",fig.pos="H"}
  plts<-rCompTCMs::compareResults.Fisheries.SelFcns(Models,
                                                    cast="y+x",
                                                    facet_grid="y~x",
                                                    mxy=5,
                                                    fleets=params$fleets,
                                                    years=params$selyears,
                                                    dodge=0,
                                                    showPlot=FALSE,
                                                    verbose=verbose);
  captions<-vector(mode="character",length=0);
  for (fplts in plts) {
    captions<-c(captions,wtsUtilities::getCaptionsFromGGPlotList(fplts));
    for (plt in fplts) {
      print(plt); cat("\n\n"); fig<-fig+1;
    }
  }
  rm(plt,fplts,plts);
```

\FloatBarrier

\clearpage 

# Retention functions

```{r EFCs03.RetFcns,results='asis',fig.height=6.5,fig.width=6.5,out.width="6.5in",fig.cap=captions,eval.after="fig.cap",fig.pos="H"}
  plts<-rCompTCMs::compareResults.Fisheries.RetFcns(Models,
                                                    cast="y+x",
                                                    facet_grid="y~x",
                                                    mxy=5,
                                                    fleets=params$fleets,
                                                    years=params$retyears,
                                                    dodge=0,
                                                    showPlot=FALSE,
                                                    verbose=verbose);
  captions<-vector(mode="character",length=0);
  for (fplts in plts) {
    captions<-c(captions,wtsUtilities::getCaptionsFromGGPlotList(fplts));
    for (plt in fplts) {
      print(plt); cat("\n\n"); fig<-fig+1;
    }
  }
  rm(plt,fplts,plts);
```

