---
author: "William Stockhausen"
date: '`r format(Sys.Date(),"%d %B, %Y")`'
params: 
    Models: none
    title: "Tanner Crab Model Fits to 'Other' Data" 
    plot1stObs: TRUE
    doc_type: "pdf"
output: 
    word_document: 
        reference_docx: '`r system.file("rmd/StylesforRmdDocs.docx",package="wtsUtilities")`'
    pdf_document: 
        toc: TRUE
        fig_width: 6.5
        fig_height: 4.0
        fig_crop: FALSE
        fig_caption: TRUE
        includes:
          in_header: '`r system.file("rmd/StylesforRmdPDFs.sty",package="wtsUtilities")`'
fontsize: 11pt
title: '`r params$title`'
---

```{r setupModelFits.OtherData, include=FALSE}
    ##input model list
    Models<-params$Models;
    doc_type<-params$doc_type;
    plot1stObs<-params$plot1stObs;
    
    ##set appendix letter
    app="A";
    ##set knitr options for subsequent chunks
    knitr::opts_chunk$set(echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, concordance=TRUE, fig.width=6.5, fig.height=7.0, dpi=300)
    
    ##set caption numbering
    if (!exists("fig")){
      fig<-1;#figures
      tbl<-0;#tables
    }
    
    cases<-names(Models);
    nCases<-length(cases);
```

#Model fits to "other" data

##Growth data

```{r plotFits.GrowthData,results='asis',fig.height=6.5,fig.width=6.5,out.width="6.5in",fig.cap=captions,eval.after="fig.cap",fig.pos="H"}
  plts<-rCompTCMs::compareFits.GrowthData(Models,plot1stObs=plot1stObs,showPlot=FALSE,verbose=FALSE)
  if (!is.null(plts)) {
    captions<-wtsUtilities::getCaptionsFromGGPlotList(plts);
    for (plt in plts) {print(plt); cat("\n\n"); fig<-fig+1;}
    rm(plt,plts);
  } else{
    cat("No growth data was fit.\n\n")
  }
```

\FloatBarrier

\clearpage

##Maturity data

```{r plotFits.MaturityData,results='asis',fig.height=6.5,fig.width=6.5,out.width="6.5in",fig.cap=captions,eval.after="fig.cap",fig.pos="H"}
  plts<-rCompTCMs::compareFits.MaturityData(Models,plot1stObs=plot1stObs,showPlot=FALSE,verbose=FALSE)
  if (!is.null(plts)) {
    captions<-wtsUtilities::getCaptionsFromGGPlotList(plts);
    for (plt in plts) {print(plt); cat("\n\n"); fig<-fig+1;}
    rm(plt,plts);
  } else{
    cat("No maturity data was fit.\n\n")
  }
```

